### ISSUE TITLE
Forgot Password Page Error and Mail Error

### ISSUE THREAD

**Issue by dwitrnd** [dwitrnd/NEWDRM#165]
Please fix the following error on `forgot-password` route:

Also verify the status of mail for leaves, there seems to be problem on that

![Image](https://github.com/user-attachments/assets/bbb5f2c1-0f90-448f-903a-ad302a1287ce)

**Comment by iamSuyas** [comment]
Made changes in the .env file:
replaced the MAIL_PASSWORD,
added MAIL_FROM_ADDRESS
added MAIL_FROM_NAME

to fix the issue
